update code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -21,36 +21,36 @@ commands:
             sudo apt install ansible
 
   destroy-environment:
-    parameters:
-      workflow_id:
-        type: string
     steps:
       - run:
           name: Destroying environment
           when: on_fail
           command: |
-            echo "Destroying environment: <<parameters.workflow_id>>"
-            aws s3 rm s3://udapeople-<<parameters.workflow_id>> --recursive
-            aws s3 wait bucket-empty s3://udapeople-<<parameters.workflow_id>>
-            aws cloudformation delete-stack --stack-name "udapeople-backend-<<parameters.workflow_id>>"
-            aws cloudformation delete-stack --stack-name "udapeople-frontend-<<parameters.workflow_id>>"
-
-
+            echo "Destroying environment: ${CIRCLE_WORKFLOW_ID:0:5}"
+            aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5}" --recursive
+            sleep 5
+            aws cloudformation delete-stack --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:5}"
+            aws cloudformation delete-stack --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:5}"
+  
   revert-migrations:
-    parameters:
-      workflow_id:
-        type: string
     steps:
       - run:
           name: Reverting migrations
           when: on_fail
           command: |
-            SUCCESS=$(curl "https://kvdb.io/8X9Rovk3quXuGkVm81MvbT/migration_<<parameters.workflow_id>>" -H "X-Api-Key: ${THISDB_API_KEY}")
-            if (($SUCCESS == 1)); then
+            echo "Reverting migrations: ${CIRCLE_WORKFLOW_ID:0:5}"
+            set -e
+            SUCCESS=$(curl --insecure https://kvdb.io/8p64HNePskjHL3HqkfRnUC/migration_${CIRCLE_WORKFLOW_ID:0:5})
+            if [ $SUCCESS == 1 ];
+            then
               cd backend
               npm install
               npm run migrations:revert
+              echo "Migrations reverted."
+            else
+              echo "Migration status not found or not successful. Skip reverting."
             fi
+
 
   install_ansible:
     description: Install Ansible
@@ -212,8 +212,7 @@ jobs:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'        
+      - destroy-environment
 
   configure-infrastructure:
     docker:
@@ -244,8 +243,7 @@ jobs:
           paths:
             - project/backend
 
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'            
+      - destroy-environment
 
   run-migrations:
     docker:
@@ -263,17 +261,20 @@ jobs:
             cd backend
             npm install
             npm run migrations > migrations_dump.txt
+            cat migrations_dump.txt
       - run:
           name: Send migration results to Kvdb or memstash
           command: |
+            echo "Saving migrations: ${CIRCLE_WORKFLOW_ID:0:5}"
             if grep -q "executed successfully" ~/project/backend/migrations_dump.txt
             then
-              curl --insecure https://kvdb.io/8X9Rovk3quXuGkVm81MvbT/migration_$\{CIRCLE_WORKFLOW_ID:0:5\} -d '1'
+              curl --insecure https://kvdb.io/8p64HNePskjHL3HqkfRnUC/migration_${CIRCLE_WORKFLOW_ID:0:5} -d '1'
+              echo "Saved migration!"
+            else
+              echo "Skip migration!"
             fi
-      - revert-migrations:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
+      - revert-migrations
+      - destroy-environment
 
   deploy-frontend:
     docker:
@@ -284,10 +285,6 @@ jobs:
           keys:
             - build-frontend
       - dependencies
-      # - run:
-      #     name: Install dependencies
-      #     command: |
-      #       # your code here
       - run:
           name: Get backend url
           command: |
@@ -302,8 +299,7 @@ jobs:
             npm run build
             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:5}".tar.gz dist
             aws s3 cp dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:5}" --recursive
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'     
+      - destroy-environment     
                     
   deploy-backend:
     docker:
@@ -316,7 +312,7 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible
+            apk add --update --no-cache tar gzip nodejs npm aws-cli ansible curl
       - restore_cache:
           keys: [backend-build]
       - attach_workspace:
@@ -336,10 +332,8 @@ jobs:
             cd .circleci/ansible
             echo "Contents of the inventory.txt file is ------$(cat inventory.txt)"
             ansible-playbook -i inventory.txt deploy-backend.yml
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
-      - revert-migrations:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'  
+      - destroy-environment
+      - revert-migrations  
 
   smoke-test-backend:
     docker:
@@ -364,10 +358,8 @@ jobs:
               else
                 exit 1
               fi
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
-      - revert-migrations:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}' 
+      - destroy-environment
+      - revert-migrations 
 
   smoke-test-frontend:
     docker:
@@ -384,7 +376,7 @@ jobs:
       - run:
           name: Smoke test for front end
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:5}.s3-website-us-east-1.amazonaws.com"             
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:5}.s3-website-us-west-1.amazonaws.com"             
             echo ${URL} 
             if curl -s ${URL} | grep "Welcome"
             then
@@ -392,10 +384,8 @@ jobs:
             else
               exit 1
             fi
-      - destroy-environment:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
-      - revert-migrations:
-          workflow_id: '${CIRCLE_WORKFLOW_ID:0:5}'
+      - destroy-environment
+      - revert-migrations
 
   cloudfront-update:
     docker:
@@ -409,8 +399,7 @@ jobs:
             OldWorkflowID=$(aws cloudformation \
             list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
             --no-paginate --output text)
-            curl https://kvdb.io/LHFkzdfqGQiT5AocazCCLL//migration_${CIRCLE_WORKFLOW_ID:0:5} \
-            -H "X-Api-Key: ${THISDB_API_KEY}" \
+            curl --insecure https://kvdb.io/8p64HNePskjHL3HqkfRnUC/migration_${CIRCLE_WORKFLOW_ID:0:5} \
             -d "$OldWorkflowID"  
       - run:
           name: Updating cloudfront distribution
@@ -420,7 +409,8 @@ jobs:
             --stack-name InitialStack \
             --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:5}" \
             --tags project=udapeople
-      # Here's where you will add some code to rollback on failure  
+      - destroy-environment
+      - revert-migrations
 
   cleanup:
     docker:
@@ -474,7 +464,7 @@ workflows:
           requires: [deploy-backend]
       - smoke-test-frontend:
           requires: [deploy-frontend]
-      # - cloudfront-update:
-      #     requires: [smoke-test-backend, smoke-test-frontend]
+      - cloudfront-update:
+          requires: [smoke-test-backend, smoke-test-frontend]
       # - cleanup:
       #     requires: [cloudfront-update]
